language: java
jdk:
  - openjdk17

# 자동화 브랜치 설정
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행
# CodeDeploy는 jar 파일을 인식하지 못하므로 (jar+기타 설정 파일) 들을  압축한다.
before_deploy:
  - zip -r springboot-aws-study *
  - mkdir -p deploy
  - mv springboot-aws-study.zip deploy/springboot-aws-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-aws-study-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCE정SS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-aws-study-build # S3 버킷
    key: springboot-aws-study.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot-aws-study # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-aws-study-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - cys74351@gmail.com
